blank_issues_enabled: false
contact_links:
  - name: "For bug reports, please check if your issue already exists before submitting."
    url: "https://github.com/IdanKoblik/R2D2/issues"
    about: "GitHub issues"
