name: Run tests

on:
  workflow_call:
    secrets:
      GIT_USER:
        required: true
      GH_AUTH:
        required: true
      GL_AUTH:
        required: true
      TESTING_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.TESTING_TOKEN }}

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone testing repos
        run: |
          mkdir -p /tmp/repo/
          git clone git@gitlab.com:IdanKoblik/gitlab.git /tmp/repo/gitlab
          git clone git@github.com:IdanKoblik/github.git /tmp/repo/github

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run integration tests
        uses: GabrielBB/xvfb-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GH_AUTH: ${{ secrets.GH_AUTH }}
          GL_AUTH: ${{ secrets.GL_AUTH }}
        with:
          run: ./gradlew check
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          detailed_summary: true
          follow_symlink: true
          check_name: |
            commands
            commands-spigot
            common
            spigot
          report_paths: |
            **/build/test-results/test/TEST-*.xml
      - name: Publish Test Report
        uses: test-summary/action@v2
        if: success() || failure()
        with:
          paths: |
            **/build/test-results/test/TEST-*.xml