name: Publish plugin

on:
  workflow_call:
    inputs:
      VERSION:
        description: 'Version name'
        required: true
        type: string
    secrets:
      GIT_USER:
        required: true
      GH_TOKEN:
        required: true
      GL_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH }}
          GIT_USER: ${{ secrets.GIT_USER }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GL_TOKEN: ${{ secrets.GL_TOKEN }}
          VERSION: ${{ inputs.VERSION }}
        run: |
          ./gradlew buildPlugin

      - name: Upload
        uses: IdanKoblik/Changelog@prod
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTH }}
        with:
          version: ${{ inputs.VERSION }}
          assets: '["./build/distributions/*.zip"]'